# 1. Introduction

## 1.1. Purpose and Scope of Literature Review

The following literature review aims to provide a comprehensive understanding of the existing body of knowledge on the concept of pressing in football, its effectiveness, and its relationship to formations. It aims to identify key findings, methodologies, and gaps in the current research to justify the need for this research undertaking. This study will establish the theoretical foundation and context for this research, ensuring that it is rooted in the existing football knowledge base by reviewing relevant literature.

The scope of the literature review is broad and multifaceted. The review will begin by exploring the role that data analysis plays in football, particularly how it aids in evaluating performance and informing tactical decisions related to pressing and formations. Next, the review will delve into how pressing is analysed in football, focusing on metrics that measure its success, the roles of players, and the various tactical approaches. Additionally, the review will discuss the different types of pressing strategies, examining their unique characteristics and the scenarios in which they are most effective.

This will be followed by a review of the analysis of formations, looking at how they shape both attacking and defensive strategies, as well as player positioning and overall gameplay.

Finally, the review will identify the gaps in existing research, specifically the lack of a quantitative link between formations and pressing effectiveness. By addressing these gaps, this study aims to contribute valuable insights for domain experts, such as coaches and analysts, in order to optimise pressing tactics based on team formations.

While peer-reviewed journal articles form the backbone of this literature review, supplementary insights from conference papers and credible blog posts have been included in order to provide contemporary insights and practical applications of formation analysis and, particularly, pressing in football.

## 1.2. The Importance of Pressing Effectiveness and its Relationship to Formations in Football

Pressing is a defensive strategy where the team without possession aggressively attempts to regain the ball. It disrupts the opponent’s build-up play, forces errors, and facilitates quick transitions to offence, making it a cornerstone of modern football [@chamberstoby2022; @morganwill2018].

Understanding pressing effectiveness is crucial in football as it directly impacts team performance [@modric2022; @modric2023]. Research shows that successful team pressing influences team technical-tactical performance (TTP) significantly, leading to increased actions like shots on target, passes, key passes, crosses, dribbles, and entries into the final third and penalty area [@modric2022; @modric2023]. Moreover, the co-operative and well-organized interaction between players during pressing plays a more vital role in TTP than pure physical performance [@modric2023]. Individual actions, such as pressing, are fundamental in modern football, with higher praxeological parameters of these actions correlating with better sports results and team performance [@modric2023]. Therefore, analysing pressing effectiveness and its relationship with formations can provide invaluable insights for coaches to optimise team strategies and player performance on the field.

## 1.3. Key Themes and Areas of Focus

# 3. Pressing Analysis in Football

## 3.1. How is Pressing Analysed in Football?

Pressing in football is currently analysed through various methods. Studies have shown that successful defensive plays exhibit higher defensive pressure, especially towards the end of a defensive sequence and closer to the ball [@forcher2022]. Automated detection of pressing strategies, like counterpressing, has been achieved using machine learning models, saving time and standardising the analysis process [@bauer2021]. Computational approaches have been proposed to estimate pressure relationships during a game, visualising defending players' pressure on the ball and opponents, aiding in detailed analysis of team tactics [@andrienko2018; @andrienko2017]. Research also indicates that successful team pressing positively influences team technical-tactical performance, emphasizing the importance of co-ordinated player interaction in pressing strategies [@modric2023]. These findings collectively highlight the significance of defensive pressure analysis in understanding and optimising team performance in football.

## 3.2. Different Types of Pressing Strategies

### 3.2.1. High Press

In football, two primary pressing strategies are commonly employed: high-press defending and deep-defending. Research by [@low2021] compared these strategies. High-press defending involves players pressing the opposition closer to their goal, aiming to win the ball back quickly and disrupt the opponent's build-up play. On the other hand, deep-defending sees players defending deeper on the field, often closer to their own goal, focusing on maintaining defensive shape and limiting space for the opposition to exploit. The study [@low2021] found that high-press defending can lead to closer centroid distances, more regular movement patterns, decreased synchronisation patterns of effective playing space, lower physical demands in terms of distance covered, and player velocity, as well as reduced heart rates compared to deep defending.

### 3.2.2. Low-Block Defence

Low-block defence in football impacts the opponent's strategy by creating challenges in breaking through the defensive line efficiently. The use of low block defence can restrict the opponent's ability to penetrate the defence due to the compact structure and reduced space available for attacking manoeuvres.

### 3.2.3. Midfield Press

The midfield press in football significantly influences the opponent's strategy by applying pressure and disrupting their build-up play. Overall, the midfield press serves as a tactical tool to unsettle opponents, control play, and create scoring opportunities.

### 3.2.4. Counter-pressing

Counter-pressing in football significantly influences the opponent's strategy by disrupting their transition play and creating immediate offensive opportunities [@bauer2021]. This strategic approach involves quickly regaining possession after losing the ball, pressuring the opponent to make hasty decisions, and potentially leading to turnovers. By automatically identifying and analysing counter-pressing situations through machine learning techniques, teams can assess the effectiveness of this tactic in terms of winning the ball back swiftly, generating scoring chances, and determining key success factors. The ability to adjust the counter pressure exerted on the opponent based on the forward pressure applied by the pressing team enhances the effectiveness of this strategy, creating a dynamic and adaptive defensive approach. Additionally, utilising counter-pressing can have defensive and offensive consequences for both teams, impacting the flow and outcome of the game.

# 4. Formation Analysis and Gameplay Influence

## 4.1. How are Formations Currently Analysed?

## 4.2. Influence of Formations on Attacking and Defensive Strategies in Football

Tactical situations and playing styles are crucial performance indicators in soccer, influencing team strategies and outcomes. Research has shown significant differences in attack styles between European and South American teams, with European teams excelling in fast and positional attacks, while South American teams focus more on shots from outside the box and off-target shots . Additionally, a study comparing different age groups in football found that First teams demonstrate more final third entries, passes, crosses, and build-up play in wide areas compared to younger teams, highlighting the evolution of playing styles with age and experience [@dayusjacob2021]. Moreover, the impact of external factors like the COVID-19 pandemic has led to changes in performance indicators over the years, resulting in a more passive game with tighter results, emphasizing the need for teams to adapt their playing styles accordingly 

## 4.3. How Formations Impact Player Roles, Defensive Shape, Pressing Strategies. and Overall Gameplay

## 4.4. Commonly Used Formations in Football

# 2. Machine Learning and Automated Analysis

## 2.1. The Role of Data Analysis in Football Performance Evaluation

Football is an inherently dynamic and unpredictable sport, requiring complex and multifaceted strategies for success [@herold2019]. Traditionally, performance analysis in football has relied on statistics derived from notational analysis based on observational match events such as team possession, shots on targets, successful passes [@plakias2024; @rein2016; @herold2019]. Match event data is typically collected from video footage and assists coaches and analysts evaluate past football matches and prepare for future games [@herold2019]. However, these metrics often discard critical contextual information necessary for comprehensive tactical analysis [@rein2016].

The dearth of knowledge on how various factors such as technical skill, individual physiology, and team formations hampers our understanding of how these factors affect tactical decision-making [@rein2016].

## 2.2. The Use of Statistical Methods, Machine Learning Techniques, and Data Visualisation Tools in Football Analysis

Machine learning applications in men's professional football have been instrumental in enhancing attacking play. Studies have shown that expected goals (xG) models developed using machine learning techniques like Logistic Regression and Gradient Boosting can accurately predict xG probability values for players based on shots taken during matches [@hewitt2023]. Additionally, the analysis of key performance indicators related to attacking play in football has been a common practice among coaches and analysts, emphasizing the importance of leveraging data-driven insights to improve offensive strategies in professional football [@herold2019].

## 2.3. Recent Advances in Data-Driven Approaches to Studying Pressing Effectiveness and Formation Dynamics

# 5. Gap in Existing Literature: Pressing and Formations

# 6. Conclusion and Proposal Contribution

```{=latex}
\newpage
```
# Bibliography
